// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.satalia.solveengine.converter;

public final class Converter {
  private Converter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_converter_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_converter_Result_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_converter_Variable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_converter_Variable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017converter.proto\022\020solver.converter\"\200\001\n\006" +
      "Result\022\016\n\006status\030\001 \001(\t\022*\n\017objective_valu" +
      "e\030\002 \001(\001H\000R\017objective_value\022-\n\tvariables\030" +
      "\003 \003(\0132\032.solver.converter.VariableB\013\n\tobj" +
      "_value\"0\n\010Variable\022\014\n\004name\030\001 \001(\t\022\017\n\005valu" +
      "e\030\002 \001(\001H\000B\005\n\003valB0\n!com.satalia.solveeng" +
      "ine.converterP\001Z\tconverterb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_solver_converter_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_solver_converter_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_converter_Result_descriptor,
        new java.lang.String[] { "Status", "ObjectiveValue", "Variables", "ObjValue", });
    internal_static_solver_converter_Variable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_solver_converter_Variable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_converter_Variable_descriptor,
        new java.lang.String[] { "Name", "Value", "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
