// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.satalia.solveengine.converter;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.converter.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status of the job
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Status of the job
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>double objective_value = 2[json_name = "objective_value"];</code>
   */
  double getObjectiveValue();

  /**
   * <pre>
   * A list of variables
   * </pre>
   *
   * <code>repeated .solver.converter.Variable variables = 3;</code>
   */
  java.util.List<com.satalia.solveengine.converter.Variable> 
      getVariablesList();
  /**
   * <pre>
   * A list of variables
   * </pre>
   *
   * <code>repeated .solver.converter.Variable variables = 3;</code>
   */
  com.satalia.solveengine.converter.Variable getVariables(int index);
  /**
   * <pre>
   * A list of variables
   * </pre>
   *
   * <code>repeated .solver.converter.Variable variables = 3;</code>
   */
  int getVariablesCount();
  /**
   * <pre>
   * A list of variables
   * </pre>
   *
   * <code>repeated .solver.converter.Variable variables = 3;</code>
   */
  java.util.List<? extends com.satalia.solveengine.converter.VariableOrBuilder> 
      getVariablesOrBuilderList();
  /**
   * <pre>
   * A list of variables
   * </pre>
   *
   * <code>repeated .solver.converter.Variable variables = 3;</code>
   */
  com.satalia.solveengine.converter.VariableOrBuilder getVariablesOrBuilder(
      int index);

  public com.satalia.solveengine.converter.Result.ObjValueCase getObjValueCase();
}
