// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: converter.proto

package com.satalia.solveengine.converter;

public interface VariableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.converter.Variable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Variable name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Variable name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double value = 2;</code>
   */
  double getValue();

  public com.satalia.solveengine.converter.Variable.ValCase getValCase();
}
