// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface CreateJobResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.CreateJobResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the newly created job
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * The ID of the newly created job
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
