// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface JobListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.JobList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  java.util.List<com.satalia.solveengine.jobsvc.JobMessage> 
      getJobsList();
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  com.satalia.solveengine.jobsvc.JobMessage getJobs(int index);
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  int getJobsCount();
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  java.util.List<? extends com.satalia.solveengine.jobsvc.JobMessageOrBuilder> 
      getJobsOrBuilderList();
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  com.satalia.solveengine.jobsvc.JobMessageOrBuilder getJobsOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   */
  int getTotal();

  public com.satalia.solveengine.jobsvc.JobList.TotalObjCase getTotalObjCase();
}
