// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

/**
 * <pre>
 * A list of jobs
 * </pre>
 *
 * Protobuf type {@code solver.jobs.JobList}
 */
public  final class JobList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solver.jobs.JobList)
    JobListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobList.newBuilder() to construct.
  private JobList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobList() {
    jobs_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              jobs_ = new java.util.ArrayList<com.satalia.solveengine.jobsvc.JobMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobs_.add(
                input.readMessage(com.satalia.solveengine.jobsvc.JobMessage.parser(), extensionRegistry));
            break;
          }
          case 16: {
            totalObjCase_ = 2;
            totalObj_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        jobs_ = java.util.Collections.unmodifiableList(jobs_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.satalia.solveengine.jobsvc.JobList.class, com.satalia.solveengine.jobsvc.JobList.Builder.class);
  }

  private int bitField0_;
  private int totalObjCase_ = 0;
  private java.lang.Object totalObj_;
  public enum TotalObjCase
      implements com.google.protobuf.Internal.EnumLite {
    TOTAL(2),
    TOTALOBJ_NOT_SET(0);
    private final int value;
    private TotalObjCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TotalObjCase valueOf(int value) {
      return forNumber(value);
    }

    public static TotalObjCase forNumber(int value) {
      switch (value) {
        case 2: return TOTAL;
        case 0: return TOTALOBJ_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TotalObjCase
  getTotalObjCase() {
    return TotalObjCase.forNumber(
        totalObjCase_);
  }

  public static final int JOBS_FIELD_NUMBER = 1;
  private java.util.List<com.satalia.solveengine.jobsvc.JobMessage> jobs_;
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  public java.util.List<com.satalia.solveengine.jobsvc.JobMessage> getJobsList() {
    return jobs_;
  }
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  public java.util.List<? extends com.satalia.solveengine.jobsvc.JobMessageOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  public com.satalia.solveengine.jobsvc.JobMessage getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
   */
  public com.satalia.solveengine.jobsvc.JobMessageOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  /**
   * <code>int32 total = 2;</code>
   */
  public int getTotal() {
    if (totalObjCase_ == 2) {
      return (java.lang.Integer) totalObj_;
    }
    return 0;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobs_.size(); i++) {
      output.writeMessage(1, jobs_.get(i));
    }
    if (totalObjCase_ == 2) {
      output.writeInt32(
          2, (int)((java.lang.Integer) totalObj_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobs_.get(i));
    }
    if (totalObjCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            2, (int)((java.lang.Integer) totalObj_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.satalia.solveengine.jobsvc.JobList)) {
      return super.equals(obj);
    }
    com.satalia.solveengine.jobsvc.JobList other = (com.satalia.solveengine.jobsvc.JobList) obj;

    boolean result = true;
    result = result && getJobsList()
        .equals(other.getJobsList());
    result = result && getTotalObjCase().equals(
        other.getTotalObjCase());
    if (!result) return false;
    switch (totalObjCase_) {
      case 2:
        result = result && (getTotal()
            == other.getTotal());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobsCount() > 0) {
      hash = (37 * hash) + JOBS_FIELD_NUMBER;
      hash = (53 * hash) + getJobsList().hashCode();
    }
    switch (totalObjCase_) {
      case 2:
        hash = (37 * hash) + TOTAL_FIELD_NUMBER;
        hash = (53 * hash) + getTotal();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.satalia.solveengine.jobsvc.JobList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of jobs
   * </pre>
   *
   * Protobuf type {@code solver.jobs.JobList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solver.jobs.JobList)
      com.satalia.solveengine.jobsvc.JobListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satalia.solveengine.jobsvc.JobList.class, com.satalia.solveengine.jobsvc.JobList.Builder.class);
    }

    // Construct using com.satalia.solveengine.jobsvc.JobList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobsBuilder_.clear();
      }
      totalObjCase_ = 0;
      totalObj_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobList_descriptor;
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobList getDefaultInstanceForType() {
      return com.satalia.solveengine.jobsvc.JobList.getDefaultInstance();
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobList build() {
      com.satalia.solveengine.jobsvc.JobList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobList buildPartial() {
      com.satalia.solveengine.jobsvc.JobList result = new com.satalia.solveengine.jobsvc.JobList(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (jobsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          jobs_ = java.util.Collections.unmodifiableList(jobs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobs_ = jobs_;
      } else {
        result.jobs_ = jobsBuilder_.build();
      }
      if (totalObjCase_ == 2) {
        result.totalObj_ = totalObj_;
      }
      result.bitField0_ = to_bitField0_;
      result.totalObjCase_ = totalObjCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.satalia.solveengine.jobsvc.JobList) {
        return mergeFrom((com.satalia.solveengine.jobsvc.JobList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.satalia.solveengine.jobsvc.JobList other) {
      if (other == com.satalia.solveengine.jobsvc.JobList.getDefaultInstance()) return this;
      if (jobsBuilder_ == null) {
        if (!other.jobs_.isEmpty()) {
          if (jobs_.isEmpty()) {
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobsIsMutable();
            jobs_.addAll(other.jobs_);
          }
          onChanged();
        }
      } else {
        if (!other.jobs_.isEmpty()) {
          if (jobsBuilder_.isEmpty()) {
            jobsBuilder_.dispose();
            jobsBuilder_ = null;
            jobs_ = other.jobs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobsFieldBuilder() : null;
          } else {
            jobsBuilder_.addAllMessages(other.jobs_);
          }
        }
      }
      switch (other.getTotalObjCase()) {
        case TOTAL: {
          setTotal(other.getTotal());
          break;
        }
        case TOTALOBJ_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.satalia.solveengine.jobsvc.JobList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.satalia.solveengine.jobsvc.JobList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int totalObjCase_ = 0;
    private java.lang.Object totalObj_;
    public TotalObjCase
        getTotalObjCase() {
      return TotalObjCase.forNumber(
          totalObjCase_);
    }

    public Builder clearTotalObj() {
      totalObjCase_ = 0;
      totalObj_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.util.List<com.satalia.solveengine.jobsvc.JobMessage> jobs_ =
      java.util.Collections.emptyList();
    private void ensureJobsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        jobs_ = new java.util.ArrayList<com.satalia.solveengine.jobsvc.JobMessage>(jobs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.satalia.solveengine.jobsvc.JobMessage, com.satalia.solveengine.jobsvc.JobMessage.Builder, com.satalia.solveengine.jobsvc.JobMessageOrBuilder> jobsBuilder_;

    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public java.util.List<com.satalia.solveengine.jobsvc.JobMessage> getJobsList() {
      if (jobsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobs_);
      } else {
        return jobsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public int getJobsCount() {
      if (jobsBuilder_ == null) {
        return jobs_.size();
      } else {
        return jobsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public com.satalia.solveengine.jobsvc.JobMessage getJobs(int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);
      } else {
        return jobsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder setJobs(
        int index, com.satalia.solveengine.jobsvc.JobMessage value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.set(index, value);
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder setJobs(
        int index, com.satalia.solveengine.jobsvc.JobMessage.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder addJobs(com.satalia.solveengine.jobsvc.JobMessage value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder addJobs(
        int index, com.satalia.solveengine.jobsvc.JobMessage value) {
      if (jobsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobsIsMutable();
        jobs_.add(index, value);
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder addJobs(
        com.satalia.solveengine.jobsvc.JobMessage.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder addJobs(
        int index, com.satalia.solveengine.jobsvc.JobMessage.Builder builderForValue) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends com.satalia.solveengine.jobsvc.JobMessage> values) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobs_);
        onChanged();
      } else {
        jobsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder clearJobs() {
      if (jobsBuilder_ == null) {
        jobs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public Builder removeJobs(int index) {
      if (jobsBuilder_ == null) {
        ensureJobsIsMutable();
        jobs_.remove(index);
        onChanged();
      } else {
        jobsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public com.satalia.solveengine.jobsvc.JobMessage.Builder getJobsBuilder(
        int index) {
      return getJobsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public com.satalia.solveengine.jobsvc.JobMessageOrBuilder getJobsOrBuilder(
        int index) {
      if (jobsBuilder_ == null) {
        return jobs_.get(index);  } else {
        return jobsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public java.util.List<? extends com.satalia.solveengine.jobsvc.JobMessageOrBuilder> 
         getJobsOrBuilderList() {
      if (jobsBuilder_ != null) {
        return jobsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobs_);
      }
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public com.satalia.solveengine.jobsvc.JobMessage.Builder addJobsBuilder() {
      return getJobsFieldBuilder().addBuilder(
          com.satalia.solveengine.jobsvc.JobMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public com.satalia.solveengine.jobsvc.JobMessage.Builder addJobsBuilder(
        int index) {
      return getJobsFieldBuilder().addBuilder(
          index, com.satalia.solveengine.jobsvc.JobMessage.getDefaultInstance());
    }
    /**
     * <pre>
     * A list of jobs
     * </pre>
     *
     * <code>repeated .solver.jobs.JobMessage jobs = 1;</code>
     */
    public java.util.List<com.satalia.solveengine.jobsvc.JobMessage.Builder> 
         getJobsBuilderList() {
      return getJobsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.satalia.solveengine.jobsvc.JobMessage, com.satalia.solveengine.jobsvc.JobMessage.Builder, com.satalia.solveengine.jobsvc.JobMessageOrBuilder> 
        getJobsFieldBuilder() {
      if (jobsBuilder_ == null) {
        jobsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.satalia.solveengine.jobsvc.JobMessage, com.satalia.solveengine.jobsvc.JobMessage.Builder, com.satalia.solveengine.jobsvc.JobMessageOrBuilder>(
                jobs_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        jobs_ = null;
      }
      return jobsBuilder_;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public int getTotal() {
      if (totalObjCase_ == 2) {
        return (java.lang.Integer) totalObj_;
      }
      return 0;
    }
    /**
     * <code>int32 total = 2;</code>
     */
    public Builder setTotal(int value) {
      totalObjCase_ = 2;
      totalObj_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2;</code>
     */
    public Builder clearTotal() {
      if (totalObjCase_ == 2) {
        totalObjCase_ = 0;
        totalObj_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solver.jobs.JobList)
  }

  // @@protoc_insertion_point(class_scope:solver.jobs.JobList)
  private static final com.satalia.solveengine.jobsvc.JobList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.satalia.solveengine.jobsvc.JobList();
  }

  public static com.satalia.solveengine.jobsvc.JobList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobList>
      PARSER = new com.google.protobuf.AbstractParser<JobList>() {
    @java.lang.Override
    public JobList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.satalia.solveengine.jobsvc.JobList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

