// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

/**
 * <pre>
 * A job message
 * </pre>
 *
 * Protobuf type {@code solver.jobs.JobMessage}
 */
public  final class JobMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solver.jobs.JobMessage)
    JobMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobMessage.newBuilder() to construct.
  private JobMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobMessage() {
    userId_ = 0;
    id_ = "";
    status_ = "";
    algorithm_ = "";
    filenames_ = "";
    dataFilenames_ = "";
    timeout_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JobMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            algorithm_ = s;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (submitted_ != null) {
              subBuilder = submitted_.toBuilder();
            }
            submitted_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(submitted_);
              submitted_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (started_ != null) {
              subBuilder = started_.toBuilder();
            }
            started_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(started_);
              started_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (finished_ != null) {
              subBuilder = finished_.toBuilder();
            }
            finished_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(finished_);
              finished_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            filenames_ = s;
            break;
          }
          case 72: {
            timeCase_ = 9;
            time_ = input.readInt32();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            dataFilenames_ = s;
            break;
          }
          case 88: {

            timeout_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.satalia.solveengine.jobsvc.JobMessage.class, com.satalia.solveengine.jobsvc.JobMessage.Builder.class);
  }

  private int timeCase_ = 0;
  private java.lang.Object time_;
  public enum TimeCase
      implements com.google.protobuf.Internal.EnumLite {
    USED_TIME(9),
    TIME_NOT_SET(0);
    private final int value;
    private TimeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TimeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TimeCase forNumber(int value) {
      switch (value) {
        case 9: return USED_TIME;
        case 0: return TIME_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public TimeCase
  getTimeCase() {
    return TimeCase.forNumber(
        timeCase_);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private int userId_;
  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>int32 user_id = 1[json_name = "user_id"];</code>
   */
  public int getUserId() {
    return userId_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object status_;
  /**
   * <pre>
   * Job status
   * </pre>
   *
   * <code>string status = 3;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Job status
   * </pre>
   *
   * <code>string status = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALGORITHM_FIELD_NUMBER = 4;
  private volatile java.lang.Object algorithm_;
  /**
   * <pre>
   * The job algorithm
   * </pre>
   *
   * <code>string algorithm = 4;</code>
   */
  public java.lang.String getAlgorithm() {
    java.lang.Object ref = algorithm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      algorithm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The job algorithm
   * </pre>
   *
   * <code>string algorithm = 4;</code>
   */
  public com.google.protobuf.ByteString
      getAlgorithmBytes() {
    java.lang.Object ref = algorithm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      algorithm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBMITTED_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp submitted_;
  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  public boolean hasSubmitted() {
    return submitted_ != null;
  }
  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  public com.google.protobuf.Timestamp getSubmitted() {
    return submitted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submitted_;
  }
  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getSubmittedOrBuilder() {
    return getSubmitted();
  }

  public static final int STARTED_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp started_;
  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  public boolean hasStarted() {
    return started_ != null;
  }
  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  public com.google.protobuf.Timestamp getStarted() {
    return started_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : started_;
  }
  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getStartedOrBuilder() {
    return getStarted();
  }

  public static final int FINISHED_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp finished_;
  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  public boolean hasFinished() {
    return finished_ != null;
  }
  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  public com.google.protobuf.Timestamp getFinished() {
    return finished_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : finished_;
  }
  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getFinishedOrBuilder() {
    return getFinished();
  }

  public static final int FILENAMES_FIELD_NUMBER = 8;
  private volatile java.lang.Object filenames_;
  /**
   * <pre>
   * Filenames
   * </pre>
   *
   * <code>string filenames = 8;</code>
   */
  public java.lang.String getFilenames() {
    java.lang.Object ref = filenames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      filenames_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Filenames
   * </pre>
   *
   * <code>string filenames = 8;</code>
   */
  public com.google.protobuf.ByteString
      getFilenamesBytes() {
    java.lang.Object ref = filenames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      filenames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USED_TIME_FIELD_NUMBER = 9;
  /**
   * <code>int32 used_time = 9[json_name = "used_time"];</code>
   */
  public int getUsedTime() {
    if (timeCase_ == 9) {
      return (java.lang.Integer) time_;
    }
    return 0;
  }

  public static final int DATA_FILENAMES_FIELD_NUMBER = 10;
  private volatile java.lang.Object dataFilenames_;
  /**
   * <pre>
   * Data filenames
   * </pre>
   *
   * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
   */
  public java.lang.String getDataFilenames() {
    java.lang.Object ref = dataFilenames_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataFilenames_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Data filenames
   * </pre>
   *
   * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
   */
  public com.google.protobuf.ByteString
      getDataFilenamesBytes() {
    java.lang.Object ref = dataFilenames_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataFilenames_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEOUT_FIELD_NUMBER = 11;
  private int timeout_;
  /**
   * <pre>
   * Timeout
   * </pre>
   *
   * <code>int32 timeout = 11;</code>
   */
  public int getTimeout() {
    return timeout_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0) {
      output.writeInt32(1, userId_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
    }
    if (!getAlgorithmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, algorithm_);
    }
    if (submitted_ != null) {
      output.writeMessage(5, getSubmitted());
    }
    if (started_ != null) {
      output.writeMessage(6, getStarted());
    }
    if (finished_ != null) {
      output.writeMessage(7, getFinished());
    }
    if (!getFilenamesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, filenames_);
    }
    if (timeCase_ == 9) {
      output.writeInt32(
          9, (int)((java.lang.Integer) time_));
    }
    if (!getDataFilenamesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dataFilenames_);
    }
    if (timeout_ != 0) {
      output.writeInt32(11, timeout_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, userId_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
    }
    if (!getAlgorithmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, algorithm_);
    }
    if (submitted_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSubmitted());
    }
    if (started_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getStarted());
    }
    if (finished_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getFinished());
    }
    if (!getFilenamesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, filenames_);
    }
    if (timeCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            9, (int)((java.lang.Integer) time_));
    }
    if (!getDataFilenamesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dataFilenames_);
    }
    if (timeout_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, timeout_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.satalia.solveengine.jobsvc.JobMessage)) {
      return super.equals(obj);
    }
    com.satalia.solveengine.jobsvc.JobMessage other = (com.satalia.solveengine.jobsvc.JobMessage) obj;

    boolean result = true;
    result = result && (getUserId()
        == other.getUserId());
    result = result && getId()
        .equals(other.getId());
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && getAlgorithm()
        .equals(other.getAlgorithm());
    result = result && (hasSubmitted() == other.hasSubmitted());
    if (hasSubmitted()) {
      result = result && getSubmitted()
          .equals(other.getSubmitted());
    }
    result = result && (hasStarted() == other.hasStarted());
    if (hasStarted()) {
      result = result && getStarted()
          .equals(other.getStarted());
    }
    result = result && (hasFinished() == other.hasFinished());
    if (hasFinished()) {
      result = result && getFinished()
          .equals(other.getFinished());
    }
    result = result && getFilenames()
        .equals(other.getFilenames());
    result = result && getDataFilenames()
        .equals(other.getDataFilenames());
    result = result && (getTimeout()
        == other.getTimeout());
    result = result && getTimeCase().equals(
        other.getTimeCase());
    if (!result) return false;
    switch (timeCase_) {
      case 9:
        result = result && (getUsedTime()
            == other.getUsedTime());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + getAlgorithm().hashCode();
    if (hasSubmitted()) {
      hash = (37 * hash) + SUBMITTED_FIELD_NUMBER;
      hash = (53 * hash) + getSubmitted().hashCode();
    }
    if (hasStarted()) {
      hash = (37 * hash) + STARTED_FIELD_NUMBER;
      hash = (53 * hash) + getStarted().hashCode();
    }
    if (hasFinished()) {
      hash = (37 * hash) + FINISHED_FIELD_NUMBER;
      hash = (53 * hash) + getFinished().hashCode();
    }
    hash = (37 * hash) + FILENAMES_FIELD_NUMBER;
    hash = (53 * hash) + getFilenames().hashCode();
    hash = (37 * hash) + DATA_FILENAMES_FIELD_NUMBER;
    hash = (53 * hash) + getDataFilenames().hashCode();
    hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeout();
    switch (timeCase_) {
      case 9:
        hash = (37 * hash) + USED_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getUsedTime();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.satalia.solveengine.jobsvc.JobMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.satalia.solveengine.jobsvc.JobMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A job message
   * </pre>
   *
   * Protobuf type {@code solver.jobs.JobMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solver.jobs.JobMessage)
      com.satalia.solveengine.jobsvc.JobMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.satalia.solveengine.jobsvc.JobMessage.class, com.satalia.solveengine.jobsvc.JobMessage.Builder.class);
    }

    // Construct using com.satalia.solveengine.jobsvc.JobMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0;

      id_ = "";

      status_ = "";

      algorithm_ = "";

      if (submittedBuilder_ == null) {
        submitted_ = null;
      } else {
        submitted_ = null;
        submittedBuilder_ = null;
      }
      if (startedBuilder_ == null) {
        started_ = null;
      } else {
        started_ = null;
        startedBuilder_ = null;
      }
      if (finishedBuilder_ == null) {
        finished_ = null;
      } else {
        finished_ = null;
        finishedBuilder_ = null;
      }
      filenames_ = "";

      dataFilenames_ = "";

      timeout_ = 0;

      timeCase_ = 0;
      time_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.satalia.solveengine.jobsvc.Jobsvc.internal_static_solver_jobs_JobMessage_descriptor;
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobMessage getDefaultInstanceForType() {
      return com.satalia.solveengine.jobsvc.JobMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobMessage build() {
      com.satalia.solveengine.jobsvc.JobMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.satalia.solveengine.jobsvc.JobMessage buildPartial() {
      com.satalia.solveengine.jobsvc.JobMessage result = new com.satalia.solveengine.jobsvc.JobMessage(this);
      result.userId_ = userId_;
      result.id_ = id_;
      result.status_ = status_;
      result.algorithm_ = algorithm_;
      if (submittedBuilder_ == null) {
        result.submitted_ = submitted_;
      } else {
        result.submitted_ = submittedBuilder_.build();
      }
      if (startedBuilder_ == null) {
        result.started_ = started_;
      } else {
        result.started_ = startedBuilder_.build();
      }
      if (finishedBuilder_ == null) {
        result.finished_ = finished_;
      } else {
        result.finished_ = finishedBuilder_.build();
      }
      result.filenames_ = filenames_;
      if (timeCase_ == 9) {
        result.time_ = time_;
      }
      result.dataFilenames_ = dataFilenames_;
      result.timeout_ = timeout_;
      result.timeCase_ = timeCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.satalia.solveengine.jobsvc.JobMessage) {
        return mergeFrom((com.satalia.solveengine.jobsvc.JobMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.satalia.solveengine.jobsvc.JobMessage other) {
      if (other == com.satalia.solveengine.jobsvc.JobMessage.getDefaultInstance()) return this;
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (!other.getAlgorithm().isEmpty()) {
        algorithm_ = other.algorithm_;
        onChanged();
      }
      if (other.hasSubmitted()) {
        mergeSubmitted(other.getSubmitted());
      }
      if (other.hasStarted()) {
        mergeStarted(other.getStarted());
      }
      if (other.hasFinished()) {
        mergeFinished(other.getFinished());
      }
      if (!other.getFilenames().isEmpty()) {
        filenames_ = other.filenames_;
        onChanged();
      }
      if (!other.getDataFilenames().isEmpty()) {
        dataFilenames_ = other.dataFilenames_;
        onChanged();
      }
      if (other.getTimeout() != 0) {
        setTimeout(other.getTimeout());
      }
      switch (other.getTimeCase()) {
        case USED_TIME: {
          setUsedTime(other.getUsedTime());
          break;
        }
        case TIME_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.satalia.solveengine.jobsvc.JobMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.satalia.solveengine.jobsvc.JobMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int timeCase_ = 0;
    private java.lang.Object time_;
    public TimeCase
        getTimeCase() {
      return TimeCase.forNumber(
          timeCase_);
    }

    public Builder clearTime() {
      timeCase_ = 0;
      time_ = null;
      onChanged();
      return this;
    }


    private int userId_ ;
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>int32 user_id = 1[json_name = "user_id"];</code>
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>int32 user_id = 1[json_name = "user_id"];</code>
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * User ID
     * </pre>
     *
     * <code>int32 user_id = 1[json_name = "user_id"];</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * Job ID
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Job ID
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Job ID
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Job ID
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Job ID
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * Job status
     * </pre>
     *
     * <code>string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Job status
     * </pre>
     *
     * <code>string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Job status
     * </pre>
     *
     * <code>string status = 3;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Job status
     * </pre>
     *
     * <code>string status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Job status
     * </pre>
     *
     * <code>string status = 3;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object algorithm_ = "";
    /**
     * <pre>
     * The job algorithm
     * </pre>
     *
     * <code>string algorithm = 4;</code>
     */
    public java.lang.String getAlgorithm() {
      java.lang.Object ref = algorithm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        algorithm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The job algorithm
     * </pre>
     *
     * <code>string algorithm = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAlgorithmBytes() {
      java.lang.Object ref = algorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        algorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The job algorithm
     * </pre>
     *
     * <code>string algorithm = 4;</code>
     */
    public Builder setAlgorithm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      algorithm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The job algorithm
     * </pre>
     *
     * <code>string algorithm = 4;</code>
     */
    public Builder clearAlgorithm() {
      
      algorithm_ = getDefaultInstance().getAlgorithm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The job algorithm
     * </pre>
     *
     * <code>string algorithm = 4;</code>
     */
    public Builder setAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      algorithm_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp submitted_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> submittedBuilder_;
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public boolean hasSubmitted() {
      return submittedBuilder_ != null || submitted_ != null;
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public com.google.protobuf.Timestamp getSubmitted() {
      if (submittedBuilder_ == null) {
        return submitted_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : submitted_;
      } else {
        return submittedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public Builder setSubmitted(com.google.protobuf.Timestamp value) {
      if (submittedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        submitted_ = value;
        onChanged();
      } else {
        submittedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public Builder setSubmitted(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (submittedBuilder_ == null) {
        submitted_ = builderForValue.build();
        onChanged();
      } else {
        submittedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public Builder mergeSubmitted(com.google.protobuf.Timestamp value) {
      if (submittedBuilder_ == null) {
        if (submitted_ != null) {
          submitted_ =
            com.google.protobuf.Timestamp.newBuilder(submitted_).mergeFrom(value).buildPartial();
        } else {
          submitted_ = value;
        }
        onChanged();
      } else {
        submittedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public Builder clearSubmitted() {
      if (submittedBuilder_ == null) {
        submitted_ = null;
        onChanged();
      } else {
        submitted_ = null;
        submittedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSubmittedBuilder() {
      
      onChanged();
      return getSubmittedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSubmittedOrBuilder() {
      if (submittedBuilder_ != null) {
        return submittedBuilder_.getMessageOrBuilder();
      } else {
        return submitted_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : submitted_;
      }
    }
    /**
     * <pre>
     * When submitted
     * </pre>
     *
     * <code>.google.protobuf.Timestamp submitted = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getSubmittedFieldBuilder() {
      if (submittedBuilder_ == null) {
        submittedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSubmitted(),
                getParentForChildren(),
                isClean());
        submitted_ = null;
      }
      return submittedBuilder_;
    }

    private com.google.protobuf.Timestamp started_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startedBuilder_;
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public boolean hasStarted() {
      return startedBuilder_ != null || started_ != null;
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public com.google.protobuf.Timestamp getStarted() {
      if (startedBuilder_ == null) {
        return started_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : started_;
      } else {
        return startedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public Builder setStarted(com.google.protobuf.Timestamp value) {
      if (startedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        started_ = value;
        onChanged();
      } else {
        startedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public Builder setStarted(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startedBuilder_ == null) {
        started_ = builderForValue.build();
        onChanged();
      } else {
        startedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public Builder mergeStarted(com.google.protobuf.Timestamp value) {
      if (startedBuilder_ == null) {
        if (started_ != null) {
          started_ =
            com.google.protobuf.Timestamp.newBuilder(started_).mergeFrom(value).buildPartial();
        } else {
          started_ = value;
        }
        onChanged();
      } else {
        startedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public Builder clearStarted() {
      if (startedBuilder_ == null) {
        started_ = null;
        onChanged();
      } else {
        started_ = null;
        startedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartedBuilder() {
      
      onChanged();
      return getStartedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartedOrBuilder() {
      if (startedBuilder_ != null) {
        return startedBuilder_.getMessageOrBuilder();
      } else {
        return started_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : started_;
      }
    }
    /**
     * <pre>
     * When started
     * </pre>
     *
     * <code>.google.protobuf.Timestamp started = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartedFieldBuilder() {
      if (startedBuilder_ == null) {
        startedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStarted(),
                getParentForChildren(),
                isClean());
        started_ = null;
      }
      return startedBuilder_;
    }

    private com.google.protobuf.Timestamp finished_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> finishedBuilder_;
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public boolean hasFinished() {
      return finishedBuilder_ != null || finished_ != null;
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public com.google.protobuf.Timestamp getFinished() {
      if (finishedBuilder_ == null) {
        return finished_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : finished_;
      } else {
        return finishedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public Builder setFinished(com.google.protobuf.Timestamp value) {
      if (finishedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        finished_ = value;
        onChanged();
      } else {
        finishedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public Builder setFinished(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (finishedBuilder_ == null) {
        finished_ = builderForValue.build();
        onChanged();
      } else {
        finishedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public Builder mergeFinished(com.google.protobuf.Timestamp value) {
      if (finishedBuilder_ == null) {
        if (finished_ != null) {
          finished_ =
            com.google.protobuf.Timestamp.newBuilder(finished_).mergeFrom(value).buildPartial();
        } else {
          finished_ = value;
        }
        onChanged();
      } else {
        finishedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public Builder clearFinished() {
      if (finishedBuilder_ == null) {
        finished_ = null;
        onChanged();
      } else {
        finished_ = null;
        finishedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getFinishedBuilder() {
      
      onChanged();
      return getFinishedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFinishedOrBuilder() {
      if (finishedBuilder_ != null) {
        return finishedBuilder_.getMessageOrBuilder();
      } else {
        return finished_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : finished_;
      }
    }
    /**
     * <pre>
     * When finished
     * </pre>
     *
     * <code>.google.protobuf.Timestamp finished = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getFinishedFieldBuilder() {
      if (finishedBuilder_ == null) {
        finishedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getFinished(),
                getParentForChildren(),
                isClean());
        finished_ = null;
      }
      return finishedBuilder_;
    }

    private java.lang.Object filenames_ = "";
    /**
     * <pre>
     * Filenames
     * </pre>
     *
     * <code>string filenames = 8;</code>
     */
    public java.lang.String getFilenames() {
      java.lang.Object ref = filenames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filenames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Filenames
     * </pre>
     *
     * <code>string filenames = 8;</code>
     */
    public com.google.protobuf.ByteString
        getFilenamesBytes() {
      java.lang.Object ref = filenames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filenames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Filenames
     * </pre>
     *
     * <code>string filenames = 8;</code>
     */
    public Builder setFilenames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      filenames_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filenames
     * </pre>
     *
     * <code>string filenames = 8;</code>
     */
    public Builder clearFilenames() {
      
      filenames_ = getDefaultInstance().getFilenames();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filenames
     * </pre>
     *
     * <code>string filenames = 8;</code>
     */
    public Builder setFilenamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      filenames_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 used_time = 9[json_name = "used_time"];</code>
     */
    public int getUsedTime() {
      if (timeCase_ == 9) {
        return (java.lang.Integer) time_;
      }
      return 0;
    }
    /**
     * <code>int32 used_time = 9[json_name = "used_time"];</code>
     */
    public Builder setUsedTime(int value) {
      timeCase_ = 9;
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 used_time = 9[json_name = "used_time"];</code>
     */
    public Builder clearUsedTime() {
      if (timeCase_ == 9) {
        timeCase_ = 0;
        time_ = null;
        onChanged();
      }
      return this;
    }

    private java.lang.Object dataFilenames_ = "";
    /**
     * <pre>
     * Data filenames
     * </pre>
     *
     * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
     */
    public java.lang.String getDataFilenames() {
      java.lang.Object ref = dataFilenames_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataFilenames_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Data filenames
     * </pre>
     *
     * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
     */
    public com.google.protobuf.ByteString
        getDataFilenamesBytes() {
      java.lang.Object ref = dataFilenames_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataFilenames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Data filenames
     * </pre>
     *
     * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
     */
    public Builder setDataFilenames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataFilenames_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data filenames
     * </pre>
     *
     * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
     */
    public Builder clearDataFilenames() {
      
      dataFilenames_ = getDefaultInstance().getDataFilenames();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Data filenames
     * </pre>
     *
     * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
     */
    public Builder setDataFilenamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataFilenames_ = value;
      onChanged();
      return this;
    }

    private int timeout_ ;
    /**
     * <pre>
     * Timeout
     * </pre>
     *
     * <code>int32 timeout = 11;</code>
     */
    public int getTimeout() {
      return timeout_;
    }
    /**
     * <pre>
     * Timeout
     * </pre>
     *
     * <code>int32 timeout = 11;</code>
     */
    public Builder setTimeout(int value) {
      
      timeout_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timeout
     * </pre>
     *
     * <code>int32 timeout = 11;</code>
     */
    public Builder clearTimeout() {
      
      timeout_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solver.jobs.JobMessage)
  }

  // @@protoc_insertion_point(class_scope:solver.jobs.JobMessage)
  private static final com.satalia.solveengine.jobsvc.JobMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.satalia.solveengine.jobsvc.JobMessage();
  }

  public static com.satalia.solveengine.jobsvc.JobMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobMessage>
      PARSER = new com.google.protobuf.AbstractParser<JobMessage>() {
    @java.lang.Override
    public JobMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JobMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JobMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.satalia.solveengine.jobsvc.JobMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

