// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface JobMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.JobMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * User ID
   * </pre>
   *
   * <code>int32 user_id = 1[json_name = "user_id"];</code>
   */
  int getUserId();

  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Job status
   * </pre>
   *
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Job status
   * </pre>
   *
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   * The job algorithm
   * </pre>
   *
   * <code>string algorithm = 4;</code>
   */
  java.lang.String getAlgorithm();
  /**
   * <pre>
   * The job algorithm
   * </pre>
   *
   * <code>string algorithm = 4;</code>
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  boolean hasSubmitted();
  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  com.google.protobuf.Timestamp getSubmitted();
  /**
   * <pre>
   * When submitted
   * </pre>
   *
   * <code>.google.protobuf.Timestamp submitted = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubmittedOrBuilder();

  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  boolean hasStarted();
  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  com.google.protobuf.Timestamp getStarted();
  /**
   * <pre>
   * When started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp started = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartedOrBuilder();

  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  boolean hasFinished();
  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  com.google.protobuf.Timestamp getFinished();
  /**
   * <pre>
   * When finished
   * </pre>
   *
   * <code>.google.protobuf.Timestamp finished = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getFinishedOrBuilder();

  /**
   * <pre>
   * Filenames
   * </pre>
   *
   * <code>string filenames = 8;</code>
   */
  java.lang.String getFilenames();
  /**
   * <pre>
   * Filenames
   * </pre>
   *
   * <code>string filenames = 8;</code>
   */
  com.google.protobuf.ByteString
      getFilenamesBytes();

  /**
   * <code>int32 used_time = 9[json_name = "used_time"];</code>
   */
  int getUsedTime();

  /**
   * <pre>
   * Data filenames
   * </pre>
   *
   * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
   */
  java.lang.String getDataFilenames();
  /**
   * <pre>
   * Data filenames
   * </pre>
   *
   * <code>string data_filenames = 10[json_name = "data_filenames"];</code>
   */
  com.google.protobuf.ByteString
      getDataFilenamesBytes();

  /**
   * <pre>
   * Timeout
   * </pre>
   *
   * <code>int32 timeout = 11;</code>
   */
  int getTimeout();

  public com.satalia.solveengine.jobsvc.JobMessage.TimeCase getTimeCase();
}
