// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface JobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.JobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the job we want to view
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * The ID of the job we want to view
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
