// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public final class Jobsvc {
  private Jobsvc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_CreateJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_CreateJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_CreateJobRequest_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_CreateJobRequest_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_Problem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_Problem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_JobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_JobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_CreateJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_CreateJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_JobStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_JobStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_JobList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_JobList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_JobMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_JobMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solver_jobs_ResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solver_jobs_ResultResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014jobsvc.proto\022\013solver.jobs\032\037google/prot" +
      "obuf/timestamp.proto\032\033google/protobuf/em" +
      "pty.proto\032\017converter.proto\"\341\001\n\020CreateJob" +
      "Request\022;\n\007options\030\001 \003(\0132*.solver.jobs.C" +
      "reateJobRequest.OptionsEntry\022&\n\010problems" +
      "\030\002 \003(\0132\024.solver.jobs.Problem\022\017\n\007timeout\030" +
      "\003 \001(\005\022\'\n\tdatafiles\030\004 \003(\0132\024.solver.jobs.P" +
      "roblem\032.\n\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\t:\0028\001\"%\n\007Problem\022\014\n\004name\030\001 \001(\t\022" +
      "\014\n\004data\030\002 \001(\014\"\030\n\nJobRequest\022\n\n\002id\030\001 \001(\t\"" +
      "\037\n\021CreateJobResponse\022\n\n\002id\030\001 \001(\t\"\033\n\tJobS" +
      "tatus\022\016\n\006status\030\001 \001(\t\"V\n\013ListRequest\022\014\n\004" +
      "page\030\001 \001(\005\022\032\n\010per_page\030\002 \001(\005R\010per_page\022\014" +
      "\n\004sort\030\003 \001(\t\022\017\n\007user_id\030\004 \001(\005\"N\n\007JobList" +
      "\022%\n\004jobs\030\001 \003(\0132\027.solver.jobs.JobMessage\022" +
      "\017\n\005total\030\002 \001(\005H\000B\013\n\ttotal_obj\"\323\002\n\nJobMes" +
      "sage\022\030\n\007user_id\030\001 \001(\005R\007user_id\022\n\n\002id\030\002 \001" +
      "(\t\022\016\n\006status\030\003 \001(\t\022\021\n\talgorithm\030\004 \001(\t\022-\n" +
      "\tsubmitted\030\005 \001(\0132\032.google.protobuf.Times" +
      "tamp\022+\n\007started\030\006 \001(\0132\032.google.protobuf." +
      "Timestamp\022,\n\010finished\030\007 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022\021\n\tfilenames\030\010 \001(\t\022\036\n\tus" +
      "ed_time\030\t \001(\005H\000R\tused_time\022&\n\016data_filen" +
      "ames\030\n \001(\tR\016data_filenames\022\017\n\007timeout\030\013 " +
      "\001(\005B\006\n\004time\"R\n\016ResultResponse\022\026\n\006job_id\030" +
      "\001 \001(\tR\006job_id\022(\n\006result\030\002 \001(\0132\030.solver.c" +
      "onverter.Result2\307\003\n\003Job\022I\n\006Create\022\035.solv" +
      "er.jobs.CreateJobRequest\032\036.solver.jobs.C" +
      "reateJobResponse\"\000\022;\n\006Status\022\027.solver.jo" +
      "bs.JobRequest\032\026.solver.jobs.JobStatus\"\000\022" +
      ";\n\007GetJobs\022\030.solver.jobs.ListRequest\032\024.s" +
      "olver.jobs.JobList\"\000\022=\n\010Schedule\022\027.solve" +
      "r.jobs.JobRequest\032\026.google.protobuf.Empt" +
      "y\"\000\022D\n\nGetResults\022\027.solver.jobs.JobReque" +
      "st\032\033.solver.jobs.ResultResponse\"\000\0229\n\004Sto" +
      "p\022\027.solver.jobs.JobRequest\032\026.google.prot" +
      "obuf.Empty\"\000\022;\n\006Delete\022\027.solver.jobs.Job" +
      "Request\032\026.google.protobuf.Empty\"\000B*\n\036com" +
      ".satalia.solveengine.jobsvcP\001Z\006jobsvcb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.satalia.solveengine.converter.Converter.getDescriptor(),
        }, assigner);
    internal_static_solver_jobs_CreateJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_solver_jobs_CreateJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_CreateJobRequest_descriptor,
        new java.lang.String[] { "Options", "Problems", "Timeout", "Datafiles", });
    internal_static_solver_jobs_CreateJobRequest_OptionsEntry_descriptor =
      internal_static_solver_jobs_CreateJobRequest_descriptor.getNestedTypes().get(0);
    internal_static_solver_jobs_CreateJobRequest_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_CreateJobRequest_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_solver_jobs_Problem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_solver_jobs_Problem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_Problem_descriptor,
        new java.lang.String[] { "Name", "Data", });
    internal_static_solver_jobs_JobRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_solver_jobs_JobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_JobRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_solver_jobs_CreateJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_solver_jobs_CreateJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_CreateJobResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_solver_jobs_JobStatus_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_solver_jobs_JobStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_JobStatus_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_solver_jobs_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_solver_jobs_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_ListRequest_descriptor,
        new java.lang.String[] { "Page", "PerPage", "Sort", "UserId", });
    internal_static_solver_jobs_JobList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_solver_jobs_JobList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_JobList_descriptor,
        new java.lang.String[] { "Jobs", "Total", "TotalObj", });
    internal_static_solver_jobs_JobMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_solver_jobs_JobMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_JobMessage_descriptor,
        new java.lang.String[] { "UserId", "Id", "Status", "Algorithm", "Submitted", "Started", "Finished", "Filenames", "UsedTime", "DataFilenames", "Timeout", "Time", });
    internal_static_solver_jobs_ResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_solver_jobs_ResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solver_jobs_ResultResponse_descriptor,
        new java.lang.String[] { "JobId", "Result", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.satalia.solveengine.converter.Converter.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
