// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface JobStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.JobStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The job status
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * The job status
   * </pre>
   *
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
