// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.ListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional page number
   * </pre>
   *
   * <code>int32 page = 1;</code>
   */
  int getPage();

  /**
   * <pre>
   * optional items per page
   * </pre>
   *
   * <code>int32 per_page = 2[json_name = "per_page"];</code>
   */
  int getPerPage();

  /**
   * <code>string sort = 3;</code>
   */
  java.lang.String getSort();
  /**
   * <code>string sort = 3;</code>
   */
  com.google.protobuf.ByteString
      getSortBytes();

  /**
   * <code>int32 user_id = 4;</code>
   */
  int getUserId();
}
