// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface ProblemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.Problem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the problem this has to include
   * the file extension
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the problem this has to include
   * the file extension
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The file content
   * </pre>
   *
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
