// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jobsvc.proto

package com.satalia.solveengine.jobsvc;

public interface ResultResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solver.jobs.ResultResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string job_id = 1[json_name = "job_id"];</code>
   */
  java.lang.String getJobId();
  /**
   * <pre>
   * Job ID
   * </pre>
   *
   * <code>string job_id = 1[json_name = "job_id"];</code>
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <pre>
   * A result object
   * </pre>
   *
   * <code>.solver.converter.Result result = 2;</code>
   */
  boolean hasResult();
  /**
   * <pre>
   * A result object
   * </pre>
   *
   * <code>.solver.converter.Result result = 2;</code>
   */
  com.satalia.solveengine.converter.Result getResult();
  /**
   * <pre>
   * A result object
   * </pre>
   *
   * <code>.solver.converter.Result result = 2;</code>
   */
  com.satalia.solveengine.converter.ResultOrBuilder getResultOrBuilder();
}
