/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sba' at '02.02.18 14:34' with Gradle 2.14.1
 *
 * @author sba, @date 02.02.18 14:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
