/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sba' at '15.12.17 14:00' with Gradle 2.14.1
 *
 * @author sba, @date 15.12.17 14:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
